# Generated by Django 3.1 on 2020-10-05 09:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20201004_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default='veg', max_length=49),
            preserve_default=False,
        ),
    ]
