# Generated by Django 3.1 on 2020-10-05 10:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Veg', 'Veg'), ('Non Veg', 'nonveg'), ('Chicken', 'chicken'), ('Mutton', 'mutton'), ('Buff', 'buff'), ('Pork', 'pork')], default='veg', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Italian', 'Italian'), ('Fast Food', 'Fast Food'), ('Japanese', 'Japanese'), ('Pizza', 'Pizza'), ('Multi Cuisine', 'Multi Cuisine')], max_length=46),
        ),
    ]
