# Generated by Django 3.1 on 2020-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20201005_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
