# Generated by Django 3.1.2 on 2020-12-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_order_table_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cover_img',
            field=models.ImageField(default='image.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
