# Generated by Django 3.1.2 on 2020-12-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20201208_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(default='image.png', upload_to='images/restaurant/category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuisine',
            name='cuisine_img',
            field=models.ImageField(default='image.png', upload_to='images/restaurant/cuisine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='profile_img',
            field=models.ImageField(default='image.png', upload_to='images/restaurant/profile'),
            preserve_default=False,
        ),
    ]
